set -g default-terminal "screen-256color"
set-option -a terminal-features "xterm-256color:RGB"

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

set -g base-index 1
setw -g pane-base-index 1
